import Head from "next/head";
import { useEffect } from "react";
import Header from "../components/header";
import Footer from "../components/footer";

const DefaultLayout = (props) => {
  return (
    <>
      <div>
        <Head>
          <title>Dishha</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <div>
          <Header />
          <div className="md:px-12 lg:px-20">
            <div className="relative" key={Math.random(0, 9) * 1000}>
              {props.children}
            </div>
          </div>
          <Footer />
        </div>
      </div>
    </>
  );
};

export default DefaultLayout;
